#!/usr/bin/env python3
"""Restore a real disposable Semaphore SQLite instance, then decrypt a task secret."""
import base64
import json
import os
from pathlib import Path
import secrets
import subprocess
import tempfile
import time
import uuid

IMAGE = 'semaphoreui/semaphore:v2.19.12@sha256:3996804607ebb63690528185bb9adc3507ee896851098e4453975f2ce7f8b435'
name = 'semaphore-restore-test-' + uuid.uuid4().hex[:10]
containers = [name, name + '-restored']
volumes = [name + '-' + suffix for suffix in ['data', 'config', 'restored-data', 'restored-config']]


def docker(*args, input=None):
    return subprocess.check_output(['docker', *args], input=input, stderr=subprocess.PIPE).decode().strip()


CLIENT = '''
import http.cookiejar,json,urllib.request,time
jar=http.cookiejar.CookieJar()
opener=urllib.request.build_opener(urllib.request.HTTPCookieProcessor(jar))
def api(path,data=None):
 req=urllib.request.Request('http://127.0.0.1:3000/api'+path,None if data is None else json.dumps(data).encode(),{'Content-Type':'application/json'})
 with opener.open(req,timeout=5) as r:
  raw=r.read();return json.loads(raw) if raw else None
import os
api('/auth/login',{'auth':'admin','password':os.environ['SEMAPHORE_ADMIN_PASSWORD']})
for c in jar:c.secure=False
'''

try:
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        env = root / 'env'
        env.write_text('SEMAPHORE_DB_DIALECT=sqlite\nSEMAPHORE_DB_HOST=/var/lib/semaphore/database.sqlite\nSEMAPHORE_ADMIN=admin\nSEMAPHORE_ADMIN_NAME=Fixture\nSEMAPHORE_ADMIN_EMAIL=fixture@localhost\nSEMAPHORE_ADMIN_PASSWORD=' + secrets.token_urlsafe(24) + '\nSEMAPHORE_ACCESS_KEY_ENCRYPTION=' + base64.b64encode(secrets.token_bytes(32)).decode() + '\n')
        env.chmod(0o600)
        for i, container in enumerate(containers):
            docker('create', '--name', container, '--network', 'none', '--env-file', str(env),
                   '-v', volumes[i * 2] + ':/var/lib/semaphore', '-v', volumes[i * 2 + 1] + ':/etc/semaphore', IMAGE)
        docker('start', name)
        for _ in range(60):
            try:
                docker('exec', name, 'python3', '-c', CLIENT)
                break
            except subprocess.CalledProcessError:
                time.sleep(1)
        else:
            raise RuntimeError('Fixture did not start')
        setup = CLIENT + r'''
from pathlib import Path
import subprocess
repo=Path('/var/lib/semaphore/repository');repo.mkdir()
(repo/'release.py').write_bytes(Path('/tmp/release.py').read_bytes())
(repo/'verify.py').write_text("import os\nfrom release import Coordinator, Journal, ReleaseError\nassert os.environ['FIXTURE_SECRET'] == 'fixture-token'\ntry:\n Coordinator({'activation_verified': True}, None, None, Journal('/var/lib/semaphore/releases')).run('web', 'main')\nexcept ReleaseError as error:\n assert 'Unreconciled' in str(error)\nelse:\n raise AssertionError('Restored checkpoint must block new releases')\nprint('Secret decryption and restart recovery gate passed')")
checkpoint=Path('/var/lib/semaphore/releases');checkpoint.mkdir()
(checkpoint/'active.json').write_text('{"stage":"migration-dispatch","status":"needs-reconciliation"}')
for cmd in [['git','init','-b','main'],['git','add','.'],['git','-c','user.name=Fixture','-c','user.email=fixture@localhost','commit','-m','fixture']]:
 subprocess.run(cmd,cwd=repo,check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
p=api('/projects',{'name':'Restore fixture','max_parallel_tasks':1})['id']
k=api(f'/project/{p}/keys',{'name':'None','type':'none','project_id':p})['id']
r=api(f'/project/{p}/repositories',{'name':'Fixture','project_id':p,'git_url':str(repo),'git_branch':'main','ssh_key_id':k})['id']
e=api(f'/project/{p}/environment',{'name':'Fixture','project_id':p,'json':'{}','env':'{}','secrets':[{'name':'FIXTURE_SECRET','type':'env','secret':'fixture-token','operation':'create'}]})['id']
t=api(f'/project/{p}/templates',{'name':'Verify','project_id':p,'app':'python','playbook':'verify.py','type':'','repository_id':r,'environment_id':e,'arguments':'[]'})['id']
print(json.dumps({'project':p,'template':t}))
'''
        docker('cp', str(Path(__file__).resolve().parents[1] / 'release.py'), name + ':/tmp/release.py')
        fixture = json.loads(docker('exec', '-i', name, 'python3', '-', input=setup.encode()))
        snapshot_script = Path(__file__).resolve().parents[1] / 'snapshot.py'
        docker('cp', str(snapshot_script), name + ':/tmp/snapshot.py')
        docker('exec', name, 'python3', '/tmp/snapshot.py', '/tmp/snapshot.tar.gz')
        docker('cp', name + ':/tmp/snapshot.tar.gz', str(root / 'snapshot.tar.gz'))
        docker('stop', name)
        import tarfile
        with tarfile.open(root / 'snapshot.tar.gz') as archive:
            archive.extractall(root / 'restore')  # Trusted archive generated by this fixture.
        restored = containers[1]
        docker('cp', str(root / 'restore/data') + '/.', restored + ':/var/lib/semaphore')
        docker('cp', str(root / 'restore/config') + '/.', restored + ':/etc/semaphore')
        docker('run', '--rm', '--network', 'none', '--user', '0', '--volumes-from', restored,
               '--entrypoint', 'sh', IMAGE, '-c', 'chown -R 1001:0 /var/lib/semaphore /etc/semaphore')
        docker('start', restored)
        for _ in range(60):
            try:
                docker('exec', restored, 'python3', '-c', CLIENT)
                break
            except subprocess.CalledProcessError:
                time.sleep(1)
        else:
            raise RuntimeError('Restored fixture did not start')
        verify = CLIENT + f'''\np={fixture['project']};t={fixture['template']}
r=api(f'/project/{{p}}/tasks',{{'template_id':t}})['id']
for _ in range(60):
 state=api(f'/project/{{p}}/tasks/{{r}}')['status']
 if state in ['success','error','stopped']:break
 time.sleep(1)
assert state=='success', state
print('Restored SQLite, login, project, repository and encrypted secret task passed')
'''
        print(docker('exec', '-i', restored, 'python3', '-', input=verify.encode()))
finally:
    for container in containers:
        subprocess.run(['docker', 'rm', '-f', container], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for volume in volumes:
        subprocess.run(['docker', 'volume', 'rm', volume], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
